mutation AddPostContent(
  $body: String!,
  $collectionId: ID!,
  $channelIds: [ID]!
) {
  addPost(
    body: $body, collectionId: $collectionId, channelIds: $channelIds
  ) {
    id
    body
    collection { id name }
    channels { id name }
  }
}
