mutation addContent($input: AddContentParams!) {
  addContent(input: $input) {
    content {
      id
      body
      collection {
        id
        name
      }
      channels {
        id
        name
      }
    }
    contentErrors {
      field
      message
    }
  }
}
