query ChannelPage($id: ID!) {
  channel(id: $id) {
    id
    name
    image
    provider
  }
  schedule(channelId: $id) {
    id
    autopilot
    timezone
    timeslots {
      id
      time
      recurrence
      collection {
        id
        name
      }
    }
  }
  collections {
    id
    name
  }
  recurrenceType: __type(name: "Recurrence") {
    enumValues {
      name
    }
  }
}
