mutation updateContent($input: UpdateContentInput!) {
  updateContent(input: $input) {
    content {
      id
      body
      channels {
        id
        name
        provider
        image
      }
    }
    contentErrors {
      field
      message
    }
  }
}
