mutation AddTimeslot(
  $scheduleId: ID!
  $collectionId: ID!
  $time: Time!
  $recurrence: Recurrence!
) {
  addTimeslot(
    timeslot: {
      time: $time
      recurrence: $recurrence
      scheduleId: $scheduleId
      collectionId: $collectionId
    }
  ) {
    id
    recurrence
    time

    collection {
      id
      name
    }
  }
}
