// flow-typed signature: 5dea81bb1e9c2fe1d54e57c726607dbe
// flow-typed version: <<STUB>>/lightgallery.js_v^1.0.1/flow_v0.44.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lightgallery.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'lightgallery.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lightgallery.js/dist/js/lightgallery' {
  declare module.exports: any;
}

declare module 'lightgallery.js/dist/js/lightgallery.min' {
  declare module.exports: any;
}

declare module 'lightgallery.js/lib/js/lg-utils' {
  declare module.exports: any;
}

declare module 'lightgallery.js/lib/js/lightgallery' {
  declare module.exports: any;
}

declare module 'lightgallery.js/src/js/lg-utils' {
  declare module.exports: any;
}

declare module 'lightgallery.js/src/js/lightgallery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lightgallery.js/dist/js/lightgallery.js' {
  declare module.exports: $Exports<'lightgallery.js/dist/js/lightgallery'>;
}
declare module 'lightgallery.js/dist/js/lightgallery.min.js' {
  declare module.exports: $Exports<'lightgallery.js/dist/js/lightgallery.min'>;
}
declare module 'lightgallery.js/lib/js/lg-utils.js' {
  declare module.exports: $Exports<'lightgallery.js/lib/js/lg-utils'>;
}
declare module 'lightgallery.js/lib/js/lightgallery.js' {
  declare module.exports: $Exports<'lightgallery.js/lib/js/lightgallery'>;
}
declare module 'lightgallery.js/src/js/lg-utils.js' {
  declare module.exports: $Exports<'lightgallery.js/src/js/lg-utils'>;
}
declare module 'lightgallery.js/src/js/lightgallery.js' {
  declare module.exports: $Exports<'lightgallery.js/src/js/lightgallery'>;
}
