// flow-typed signature: a7e43572666f650b96917004722d4fea
// flow-typed version: <<STUB>>/phoenix_html_vfile:deps/phoenix_html/flow_v0.44.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phoenix_html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'phoenix_html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'phoenix_html/brunch-config' {
  declare module.exports: any;
}

declare module 'phoenix_html/priv/static/phoenix_html' {
  declare module.exports: any;
}

declare module 'phoenix_html/web/static/js/phoenix_html' {
  declare module.exports: any;
}

// Filename aliases
declare module 'phoenix_html/brunch-config.js' {
  declare module.exports: $Exports<'phoenix_html/brunch-config'>;
}
declare module 'phoenix_html/priv/static/phoenix_html.js' {
  declare module.exports: $Exports<'phoenix_html/priv/static/phoenix_html'>;
}
declare module 'phoenix_html/web/static/js/phoenix_html.js' {
  declare module.exports: $Exports<'phoenix_html/web/static/js/phoenix_html'>;
}
