// flow-typed signature: 506b931a66b3642bb8af07348c88cf6e
// flow-typed version: <<STUB>>/phoenix_vfile:deps/phoenix/flow_v0.44.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'phoenix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'phoenix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'phoenix/brunch-config' {
  declare module.exports: any;
}

declare module 'phoenix/priv/static/phoenix' {
  declare module.exports: any;
}

declare module 'phoenix/web/static/js/phoenix' {
  declare module.exports: any;
}

declare module 'phoenix/web/test/presence_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'phoenix/brunch-config.js' {
  declare module.exports: $Exports<'phoenix/brunch-config'>;
}
declare module 'phoenix/priv/static/phoenix.js' {
  declare module.exports: $Exports<'phoenix/priv/static/phoenix'>;
}
declare module 'phoenix/web/static/js/phoenix.js' {
  declare module.exports: $Exports<'phoenix/web/static/js/phoenix'>;
}
declare module 'phoenix/web/test/presence_test.js' {
  declare module.exports: $Exports<'phoenix/web/test/presence_test'>;
}
