// flow-typed signature: 98f501db7d79d06089d4b97034b88906
// flow-typed version: <<STUB>>/turbolinks_v^5.0.0/flow_v0.44.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'turbolinks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'turbolinks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'turbolinks/dist/turbolinks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'turbolinks/dist/turbolinks.js' {
  declare module.exports: $Exports<'turbolinks/dist/turbolinks'>;
}
